// <auto-generated />
using System;
using EMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417135301_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS.API.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8258),
                            PasswordHash = "$2a$11$caF4aQAwgV6XAzbNu2XgVeRBSWTALoPefESzxtO58ianwOVDZ9Lmu",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8260),
                            PasswordHash = "$2a$11$gve9PCLry7K9q23jKtdcQ.hdc0UXII8BU8jwvcSFkLCrLrwZYucL6",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("EMS.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8394),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "harshitha.kamatam@gmail.com",
                            FirstName = "Harshitha",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kamatam",
                            Phone = "9876543289",
                            Salary = 950000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8394)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8400),
                            Department = "Marketing",
                            Designation = "Marketing Executive",
                            Email = "santhosh.kamatam@yahoo.com",
                            FirstName = "Santhosh",
                            JoinDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kamatam",
                            Phone = "9123456790",
                            Salary = 680000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8400)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8404),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "goutham.kamatam@outlook.com",
                            FirstName = "Goutham",
                            JoinDate = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kamatam",
                            Phone = "9876512398",
                            Salary = 620000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8404)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8408),
                            Department = "Finance",
                            Designation = "Financial Analyst",
                            Email = "rishitha.kola@gmail.com",
                            FirstName = "Rishitha",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kola",
                            Phone = "9989929004",
                            Salary = 990000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8408)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8411),
                            Department = "Operations",
                            Designation = "Supply chain",
                            Email = "sandy.kalisetty@gmail.com",
                            FirstName = "Sandeeep",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kalisetty",
                            Phone = "8765429876",
                            Salary = 950000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8412)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8415),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "rana.thota@gmail.com",
                            FirstName = "Ranaveer",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Thota",
                            Phone = "9872347658",
                            Salary = 850000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8415)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8418),
                            Department = "Marketing",
                            Designation = "Marketing Executive",
                            Email = "thaswin.miriyala@gmail.com",
                            FirstName = "Thaswin",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Miriyala",
                            Phone = "92244637863",
                            Salary = 950000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8419)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8422),
                            Department = "Hr",
                            Designation = "Hr Executive",
                            Email = "parthi.miriyala@gmail.com",
                            FirstName = "Parthi",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Miriyala",
                            Phone = "9933452133",
                            Salary = 750000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8422)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8426),
                            Department = "Finance",
                            Designation = "Financial Analyst",
                            Email = "jaya.km@gmail.com",
                            FirstName = "Jaya",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "MirKam",
                            Phone = "8899554474",
                            Salary = 650000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8426)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8429),
                            Department = "Operations",
                            Designation = "Supply chain",
                            Email = "veeri.korsipati@gmail.com",
                            FirstName = "Veeri",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Korsipati",
                            Phone = "9888226608",
                            Salary = 850000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8430)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8433),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "yash.thota@gmail.com",
                            FirstName = "Yaswanth",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Thota",
                            Phone = "9887351437",
                            Salary = 450000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8433)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8437),
                            Department = "Hr",
                            Designation = "HR Executive",
                            Email = "krishna.parlapalli@gmail.com",
                            FirstName = "Krishna",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Parlapalli",
                            Phone = "99977553311",
                            Salary = 950000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8437)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8440),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "ram.garre@gmail.com",
                            FirstName = "Ram",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Garre",
                            Phone = "9886644645",
                            Salary = 880000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8441)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8444),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "lucky.kamatam@gmail.com",
                            FirstName = "Lucky",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kamatam",
                            Phone = "9009865124",
                            Salary = 990000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8444)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8447),
                            Department = "Hr",
                            Designation = "HR Executive",
                            Email = "hanu.mara@gmail.com",
                            FirstName = "Hanu",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Mara",
                            Phone = "9974672431",
                            Salary = 950000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 53, 603, DateTimeKind.Utc).AddTicks(8448)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
